commands:
  update:
    shell: |
      pip3 install  .

  testrun:
    shell: |
      ic update
      ic test

  echo-test:
    shell: |
      echo abc
      echo def
      
  reset-env:
    help: resets the virtual environment
    shell: |
      rm -rf .env
      virtualenv .env
      .env/bin/activate
      pip3 install .


